"""Chinese display labels for skills catalog (sidebar UI)."""

from __future__ import annotations

# Category id -> short Chinese label for tree headers
CATEGORY_LABEL_ZH: dict[str, str] = {
    "data-source": "数据源",
    "strategy": "策略",
    "analysis": "分析",
    "asset-class": "资产类别",
    "crypto": "加密资产",
    "flow": "资金流与事件",
    "tool": "工具与文档",
    "other": "其他",
}

# Skill id -> short Chinese name (paired with English id in UI)
SKILL_NAME_ZH: dict[str, str] = {
    "adr-hshare": "跨市场 ADR/H股/A股",
    "akshare": "AKShare 开源数据",
    "asset-allocation": "资产配置",
    "backtest-diagnose": "回测诊断",
    "behavioral-finance": "行为金融",
    "candlestick": "K线形态",
    "ccxt": "CCXT 加密数据",
    "chanlun": "缠论",
    "commodity-analysis": "大宗商品",
    "convertible-bond": "可转债",
    "corporate-events": "公司事件驱动",
    "correlation-analysis": "相关与协整",
    "credit-analysis": "信用与固收",
    "crypto-derivatives": "加密衍生品",
    "data-routing": "数据源路由",
    "defi-yield": "DeFi 收益",
    "doc-reader": "PDF 文档阅读",
    "earnings-forecast": "盈利预测",
    "earnings-revision": "盈利修正",
    "edgar-sec-filings": "SEC 文件",
    "elliott-wave": "艾略特波浪",
    "etf-analysis": "ETF 分析",
    "event-driven": "事件驱动",
    "execution-model": "成交执行模型",
    "factor-research": "因子研究",
    "financial-statement": "财务报表",
    "fund-analysis": "基金分析",
    "fundamental-filter": "基本面筛选",
    "geopolitical-risk": "地缘风险",
    "global-macro": "全球宏观",
    "harmonic": "谐波形态",
    "hedging-strategy": "对冲策略",
    "hk-connect-flow": "沪深港通",
    "ichimoku": "一目均衡",
    "liquidation-heatmap": "爆仓热力",
    "macro-analysis": "宏观分析",
    "market-microstructure": "市场微观结构",
    "minute-analysis": "分钟线分析",
    "ml-strategy": "机器学习策略",
    "multi-factor": "多因子选股",
    "okx-market": "OKX 行情",
    "onchain-analysis": "链上分析",
    "options-advanced": "高阶期权",
    "options-payoff": "期权盈亏",
    "options-strategy": "期权策略",
    "pair-trading": "配对交易",
    "performance-attribution": "业绩归因",
    "perp-funding-basis": "永续与基差",
    "pine-script": "Pine 脚本导出",
    "quant-statistics": "量化统计",
    "regulatory-knowledge": "监管知识",
    "report-generate": "研报生成",
    "risk-analysis": "风险分析",
    "seasonal": "季节效应",
    "sector-rotation": "行业轮动",
    "sentiment-analysis": "市场情绪",
    "smc": "SMC 聪明钱",
    "social-media-intelligence": "社交媒体情报",
    "stablecoin-flow": "稳定币流动",
    "strategy-generate": "策略生成与回测",
    "technical-basic": "技术指标基础",
    "token-unlock-treasury": "代币解锁与金库",
    "tushare": "Tushare 数据",
    "us-etf-flow": "美股 ETF 资金流",
    "valuation-model": "估值模型",
    "volatility": "波动率策略",
    "web-reader": "网页阅读",
    "yfinance": "Yahoo 财经数据",
}

# 侧栏与弹窗用的中文一句话简介（与 SKILL.md 中英 description 独立，便于用户直接阅读）
SKILL_INTRO_ZH: dict[str, str] = {
    "adr-hshare": "跟踪美股 ADR、港股 H 股与 A 股价差，服务套利、双重上市估值与退市风险。",
    "akshare": "开源免费财经数据聚合，覆盖 A 股/美股/港股、期货与宏观，可作其他数据源的补充。",
    "asset-allocation": "现代组合理论、Black-Litterman、风险预算与全天候等配置思路及再平衡规则。",
    "backtest-diagnose": "回测失败或绩效异常时的排查步骤：数据、参数、代码与引擎契约。",
    "behavioral-finance": "过度反应、动量反转的行为解释、情绪周期与认知偏差及纠偏量化思路。",
    "candlestick": "经典 K 线形态向量识别，多空形态打分合成信号。",
    "ccxt": "统一访问百余交易所的加密现货/合约公共行情，OKX 不可用时的备选。",
    "chanlun": "分型、笔、中枢与买卖点（czsc），多周期与笔数形态分类。",
    "commodity-analysis": "油铜金等商品供需、库存、期限结构及季节性方向信号。",
    "convertible-bond": "转股/纯债/期权三维估值，下修强赎博弈与双低轮动框架。",
    "corporate-events": "并购套利、增减持、股权激励、定增配股与 ST/退市预警。",
    "correlation-analysis": "收益相关、协整、半衰期、动态对冲比与配对交易信号。",
    "credit-analysis": "信用债利差、违约与城投、可转债信用侧分析。",
    "crypto-derivatives": "永续资金费、期现结构、期权微笑与希腊值策略要点。",
    "data-routing": "回测或拉数前按市场与品种选择最优数据源（先读本技能）。",
    "defi-yield": "借贷、LP、质押与挖矿的收益与风险调整比较及协议可持续性。",
    "doc-reader": "PDF 全文与扫描页 OCR，配合 read_document 工具。",
    "earnings-forecast": "一致预期、SUE、PEAD 与业绩超预期交易思路。",
    "earnings-revision": "美股/港股盈利共识变动、业绩惊喜与管理指引跟踪。",
    "edgar-sec-filings": "10-K/10-Q/8-K、代理权与内幕 4 表，提取财务与风险因子。",
    "elliott-wave": "锯齿推动与调整浪、斐波那契比例校验与趋势/调整阶段信号。",
    "etf-analysis": "ETF 筛选、费率、跟踪误差、流动性与中国市场配置框架。",
    "event-driven": "新闻与公告事件的情绪打分与可回测事件驱动流程。",
    "execution-model": "回测用滑点、VWAP/TWAP、冲击成本与执行假设配置。",
    "factor-research": "因子 IC/IR、分层检验与多因子合成与截面评价。",
    "financial-statement": "三表勾稽、盈利质量、杜邦分解与财务造假红旗。",
    "fund-analysis": "基金筛选、晨星/夏普/风格箱、漂移与 FOF、ETF 选择。",
    "fundamental-filter": "PE/PB/ROE 等基本面筛选，A 股 tushare 与港美 yfinance。",
    "geopolitical-risk": "地缘危机前兆量化与战争、制裁、供应链冲击情景策略。",
    "global-macro": "央行、汇率、地缘与资本流动驱动的跨资产因子。",
    "harmonic": "加特利/蝙蝠/螃蟹等谐波形态与 PRZ 反转区信号。",
    "hedging-strategy": "Beta 对冲、期权保护、尾部风险与跨资产对冲比率与成本。",
    "hk-connect-flow": "沪深港通南北向资金、行业配置与跨境价差线索。",
    "ichimoku": "转换线/基准线/云区/迟行线等日系技术分析信号。",
    "liquidation-heatmap": "杠杆集中区、连环爆仓与清算密集区作支撑阻力参考。",
    "macro-analysis": "经济周期、通胀利率与汇率对股债商配置的映射。",
    "market-microstructure": "价差、订单流毒性、流动性、订单簿与 A 股交易机制。",
    "minute-analysis": "分钟 K 线获取、分析与接入回测引擎。",
    "ml-strategy": "sklearn 走步训练、特征工程与任意 OHLCV 预测信号。",
    "multi-factor": "多因子标准化、IC 加权与 TopN 截面组合。",
    "okx-market": "OKX V5 现货/衍生品行情、资金费率与持仓量等（公开接口）。",
    "onchain-analysis": "活跃地址、巨鲸、TVL、DEX 流动性及 MVRV/NVT/SOPR 等链上指标。",
    "options-advanced": "波动率曲面、动态希腊值、日历价差与偏斜套利基础。",
    "options-payoff": "期权损益图、盈亏平衡与多腿希腊值情景分析。",
    "options-strategy": "BS 定价、希腊值与多腿回测（股票与加密期权）。",
    "pair-trading": "两标的价差或比价 Z 分数均值回归，至少两个标的。",
    "performance-attribution": "Brinson 归因、因子 α/β、择时与基准对比。",
    "perp-funding-basis": "永续资金费率、期现基差与跨所套利思路。",
    "pine-script": "将策略导出为 TradingView/通达信/同花顺/东财/MT5 等脚本思路。",
    "quant-statistics": "ADF、协整、GARCH、回归诊断、Bootstrap 与假设检验。",
    "regulatory-knowledge": "A 股涨跌停与退市、港股做空、美股 PDT、加密与跨境税务常识。",
    "report-generate": "投研报告结构、Markdown 规范、评级与用语指南。",
    "risk-analysis": "VaR/CVaR、回撤、蒙特卡洛与历史情景压力测试。",
    "seasonal": "月度/星期等日历效应与任意 OHLCV 季节策略。",
    "sector-rotation": "行业景气、动量、产业链与估值/盈利/资金流多维比较。",
    "sentiment-analysis": "恐贪、Put/Call、融资融券、北向与社交舆情量化。",
    "smc": "BOS、ChoCH、FVG、订单块等 ICT/聪明钱结构信号。",
    "social-media-intelligence": "从 X/Telegram/Discord/Reddit 提取财经情绪与主题。",
    "stablecoin-flow": "稳定币铸销、交易所储备与链上速度等择时线索。",
    "strategy-generate": "编写与优化量化策略、对接 SignalEngine 与回测评估。",
    "technical-basic": "EMA/ADX/BB/RSI/OBV 等基础指标多维度投票信号。",
    "token-unlock-treasury": "代币解锁节奏、团队/投资人释放与金库抛压评估。",
    "tushare": "国内股票、基金、期货等行情与财务等标准化接口（需 token）。",
    "us-etf-flow": "美股 ETF 申赎、行业宽度与风格因子资金流。",
    "valuation-model": "DCF/DDM/SOTP 与 PE/PB/EV 等相对估值与敏感性、估值陷阱。",
    "volatility": "历史波动率分位均值回归类策略。",
    "web-reader": "URL 转 Markdown 可读正文，使用 read_url。",
    "yfinance": "Yahoo 美股/港股/ETF 行情、财报与持仓等（免费免 Key）。",
}
